name: Add Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the environment to add'
        required: true
        type: string

jobs:
  add_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check GH version
        run: gh --version

      - name: Authenticate with GitHub CLI
        run: gh auth login

      - name: Add environment to repository
        run: |
          gh repo edit ${GITHUB_REPOSITORY} --add-environment ${{ inputs.environment_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
