name: Add Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the environment to add'
        required: true
        type: string

jobs:
  add_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare python
        run: pip install pynacl
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add environment to repository
        run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.UBER_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }}

      - name: Get public repository public key
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.UBER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -o key_descriptor.txt \
            https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }}/secrets/public-key
          TMP_PUBLIC_KEY_ID=`cat key_descriptor.txt | jq -r .key_id'
          TMP_PUBLIC_KEY=`cat key_descriptor.txt | jq -r .key'
          cat key_descriptor.txt
          echo "key_id: $TMP_PUBLIC_KEY_ID"
          echo "key: $TMP_PUBLIC_KEY"
          
      - name: Encode test string
        run: |
          TMP_SECRET=`python ./scripts/encryptSecretWithKey.py $TMP_PUBLIC_KEY "SOME_VALUE_TO_STORE"`
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.UBER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }}/secrets/REAL_SECRET \
            -d '{"encrypted_value":"$TMP_SECRET","key_id":"$TMP_PUBLIC_KEY_ID"}'
