name: Add Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the environment to add'
        required: true
        type: string

jobs:
  add_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check GH version
        run: gh --version

      - name: Add environment to repository
        run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.UBER_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }}

      - name: Add secret to the environment
        run: |
          gh auth login --with-token ${{ secrets.UBER_TOKEN }}
          gh secret set SOME_SECRET --body "SOME_SECURE_TEXT"
