name: Add Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the environment to add'
        required: true
        type: string

jobs:
  add_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare python
        run: pip install pynacl
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add environment to repository
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.UBER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }}

      - name: Get repository's environment public key
        id: public_key
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.UBER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -o key_descriptor.txt \
            https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }}/secrets/public-key
          TMP_PUBLIC_KEY_ID=`cat key_descriptor.txt | jq -r .key_id`
          TMP_PUBLIC_KEY=`cat key_descriptor.txt | jq -r .key`
          echo "TMP_PUBLIC_KEY_ID=$TMP_PUBLIC_KEY_ID" >> $GITHUB_OUTPUT
          echo "TMP_PUBLIC_KEY=$TMP_PUBLIC_KEY" >> $GITHUB_OUTPUT
          
      - name: Encode test string
        run: |
          ENCRYPTED_SECRET_VALUE=`python ./scripts/encryptSecretWithKey.py ${{ steps.public_key.outputs.TMP_PUBLIC_KEY }} "SOME_VALUE_TO_STORE"`
          SECRET_NAME="REAL_SECRET"
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.UBER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }}/secrets/${SECRET_NAME} \
            -d "{\"encrypted_value\":\"${ENCRYPTED_SECRET_VALUE}\",\"key_id\":\"${{ steps.public_key.outputs.TMP_PUBLIC_KEY_ID }}\"}"
