# This is a basic workflow to help you get started with Actions

name: Display parameters

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: chmod +x ./scripts/envs.sh

      - name: Run a multi-line script
        run: ./scripts/envs.sh ${{ secrets.UBER_TOKEN }} ${{ secrets.REAL_SECRET }}
