name: Generate random string

on:
  workflow_dispatch:
    inputs:
      length:
        required: true
        type: number

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Generate random string
        run: |
          echo ${{ inputs.length }}
          THE_RESULT=`cat /dev/urandom | tr -dc 'A-Za-z0-9!@#$%^&*' | head -c ${{ inputs.length }}`
          echo $THE_RESULT
