name: Testing

on:
  push:
    tags:
      - 'testing'

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      working-environment: ${{ steps.environment-name.outputs.name}
      
    steps:
      - id: environment-name
        name: 'Evaluate environment'
        run: |
          echo "name=${{github.event_name == 'push' && 'abc' || inputs.environment }}" >> "$GITHUB_OUTPUT"
          
  use-environment:
    runs-on: ubuntu-latest
    needs: setup-environment
    environment: ${{ needs.setup-environment.outputs.name }}
      
    steps:
      - id: environment-name
        name: 'Evaluate environment'
        run: |
          echo "Evaluated: ${{ toJSON(github) }}"
          
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: ${{ env.ENV_VALUE}}

  #   steps:
  #     - name: 'Display state'
  #       run: |
  #         echo "ENV_VALUE=$ENV_VALUE"
  #         echo "Event name is: ${{ github.event_name }}"
  #         echo "Job environment is: ${{ toJSON(job) }}"
  #         echo "Github: ${{ toJSON(github) }}"
