name: Testing

on:
  push:
    tags:
      - 'testing'

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    env: 
      foo : bar
  
    steps:
      - name: 'Evaluate environment'
        run: |
          export ENV_VALUE=${{github.event_name == 'push' && 'abc' || inputs.environment }}
          echo "ENV_VALUE=$ENV_VALUE" >> $GITHUB_ENV
          echo "github env: ${{ env.ENV_VALUE }}"
          echo "GITHUB_ENV:$GITHUB_ENV"
          echo "env: ${{ toJSON(env) }}"
          
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: ${{ env.ENV_VALUE}}

  #   steps:
  #     - name: 'Display state'
  #       run: |
  #         echo "ENV_VALUE=$ENV_VALUE"
  #         echo "Event name is: ${{ github.event_name }}"
  #         echo "Job environment is: ${{ toJSON(job) }}"
  #         echo "Github: ${{ toJSON(github) }}"
